const ANILIST='https://graphql.anilist.co';
const TVMAZE='https://api.tvmaze.com/shows?page=1';
const state={items:[],saved:JSON.parse(localStorage.getItem('opai_saved')||'[]'),hero:null};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const placeholder='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="300" height="450"><rect width="100%" height="100%" fill="#171320"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#8e8798" font-family="Arial">OPAI HUB</text></svg>');
async function ani(query,vars={}){const r=await fetch(ANILIST,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables:vars})});if(!r.ok)throw Error('AniList');return r.json()}
const mediaQ=`query($type:MediaType,$sort:[MediaSort],$search:String){Page(perPage:15){media(type:$type,sort:$sort,search:$search){id title{romaji english native} coverImage{extraLarge large} bannerImage description genres averageScore episodes seasonYear status trailer{id site thumbnail} format}}}`;
const animeQ=`query{Page(perPage:15){media(type:ANIME,sort:[POPULARITY_DESC]){id title{romaji english} coverImage{extraLarge large} bannerImage description genres averageScore episodes seasonYear status trailer{id site thumbnail}}}}`;
const seriesQ=`query{Page(perPage:15){media(type:ANIME,sort:[TRENDING_DESC]){id title{romaji english} coverImage{extraLarge large} bannerImage description genres averageScore episodes seasonYear status trailer{id site thumbnail}}}}`;
function normalizeAnime(m){return {id:'a'+m.id,type:'anime',sourceId:m.id,title:m.title.english||m.title.romaji||m.title.native,image:m.coverImage?.extraLarge||m.coverImage?.large||placeholder,banner:m.bannerImage||m.coverImage?.extraLarge||placeholder,desc:(m.description||'').replace(/<[^>]*>/g,'').slice(0,280),genres:m.genres||[],score:m.averageScore,year:m.seasonYear,episodes:m.episodes,trailer:m.trailer}}
async function loadAnime(){try{const d=await ani(animeQ);const arr=d.data.Page.media.map(normalizeAnime);state.items=arr;render();if(arr[0])setHero(arr[0])}catch(e){fallback()}}
async function loadSeries(){try{const r=await fetch(TVMAZE);const shows=await r.json();const arr=shows.slice(0,15).map(s=>({id:'s'+s.id,type:'series',sourceId:s.id,title:s.name,image:s.image?.original||s.image?.medium||placeholder,banner:s.image?.original||placeholder,desc:(s.summary||'').replace(/<[^>]*>/g,'').slice(0,280),genres:s.genres||[],score:s.rating?.average,year:s.premiered?.slice(0,4),episodes:null,trailer:null}));state.series=arr;state.items=[...(state.items||[]),...arr];renderSeries(arr);renderSaved();}catch(e){renderSeries([])}}
function fallback(){const arr=[{id:'demo1',type:'anime',title:'Catálogo indisponível',image:placeholder,banner:placeholder,desc:'Não foi possível carregar o catálogo agora. Recarregue a página.',genres:['Anime']}];state.items=arr;render()}
function card(x){const saved=state.saved.includes(x.id);return `<article class="card" data-id="${esc(x.id)}"><div class="poster"><img loading="lazy" src="${x.image}" onerror="this.src='${placeholder}'"><button class="save" data-save="${esc(x.id)}">${saved?'♥':'♡'}</button></div><div class="card-title">${esc(x.title)}</div><div class="card-meta">${esc(x.type==='anime'?'Anime':'Série')} ${x.year?'• '+esc(x.year):''}${x.score?' • '+Math.round(x.score)+'/100':''}</div></article>`}
function render(){const anime=state.items.filter(x=>x.type==='anime');$('#trendingGrid').innerHTML=anime.slice(0,10).map(card).join('');$('#animeGrid').innerHTML=anime.slice(5,15).map(card).join('');$('#topAiring').innerHTML=anime.slice(0,6).map(x=>`<div class="side-card" data-id="${x.id}"><img src="${x.image}"><div><b>${esc(x.title)}</b><small>● Em exibição</small></div></div>`).join('');bindCards()}
function renderSeries(arr){$('#seriesGrid').innerHTML=arr.map(card).join('');bindCards()}
function renderSaved(){const all=state.items.filter(x=>state.saved.includes(x.id));$('#savedGrid').innerHTML=all.length?all.map(card).join(''):'<p style="color:#8e8798">Sua lista está vazia. Clique em ♡ em um título para salvar.</p>';bindCards()}
function bindCards(){document.querySelectorAll('.card,.side-card').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-save]'))return;const x=state.items.find(i=>i.id===el.dataset.id);if(x)openDetail(x)});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];localStorage.setItem('opai_saved',JSON.stringify(state.saved));render();renderSeries(state.series||[]);renderSaved()})}
function setHero(x){state.hero=x;$('#heroTitle').textContent=x.title;$('#heroMeta').textContent=`${x.type==='anime'?'Anime':'Série'} • ${(x.genres||[]).slice(0,3).join(' • ')}`;$('#heroDesc').textContent=x.desc||'Encontre sua próxima história favorita no Opai Hub.';$('#heroBg').style.backgroundImage=`url("${x.banner||x.image}")`;$('#heroWatch').onclick=()=>openDetail(x);$('#heroDetails').onclick=()=>openDetail(x)}
function openDetail(x){$('#detailBody').innerHTML=`<img class="detail-cover" src="${x.banner||x.image}"><div class="detail-body"><h2>${esc(x.title)}</h2><div class="card-meta">${esc(x.type)} ${x.year?'• '+x.year:''} ${x.score?'• Nota '+Math.round(x.score)+'/100':''}</div><p>${esc(x.desc||'Sem descrição disponível.')}</p><p>${(x.genres||[]).map(g=>`<span class="tab active" style="display:inline-block;margin:3px">${esc(g)}</span>`).join('')}</p><div class="player">${x.trailer?.site==='youtube'?`<iframe width="100%" height="100%" style="border:0;border-radius:9px" src="https://www.youtube.com/embed/${encodeURIComponent(x.trailer.id)}" allowfullscreen title="Trailer"></iframe>`:`<div><b>▶ Área de reprodução</b><p>Esta área aceita vídeos autorizados pelo provedor. Trailers oficiais podem aparecer aqui quando disponíveis.</p></div>`}</div></div>`;$('#detailModal').classList.add('open')}
async function search(q){if(!q.trim()){return $('#searchResults').innerHTML=''};$('#searchResults').innerHTML='<p style="color:#aaa">Buscando...</p>';try{const d=await ani(mediaQ,{type:'ANIME',sort:['SEARCH_MATCH'],search:q});const arr=d.data.Page.media.map(normalizeAnime);const tv=state.series||[];const tvr=tv.filter(x=>x.title.toLowerCase().includes(q.toLowerCase())).slice(0,5);$('#searchResults').innerHTML=[...arr,...tvr].slice(0,10).map(x=>`<div class="result" data-id="${x.id}"><img src="${x.image}"><div><b>${esc(x.title)}</b><small style="display:block;color:#888">${x.type==='anime'?'Anime':'Série'}</small></div></div>`).join('')||'<p>Nenhum resultado.</p>';document.querySelectorAll('.result').forEach(r=>r.onclick=()=>{const x=[...arr,...tvr].find(i=>i.id===r.dataset.id);$('#searchModal').classList.remove('open');openDetail(x)})}catch(e){$('#searchResults').innerHTML='<p>Não foi possível pesquisar agora.</p>'}}
function admin(){const body=$('#adminBody');body.innerHTML=`<h2>Área de administração</h2><p>Somente administradores devem acessar esta área.</p><div class="admin-note">⚠️ GitHub Pages é hospedagem estática. Esconder esta tela ou usar senha em JavaScript <b>não é segurança real</b>. Para administração realmente privada, use autenticação + backend (por exemplo, Supabase/Firebase) e nunca coloque senhas de administrador no código.</div><div class="admin-links"><button class="primary" onclick="location.hash='admin'">Abrir painel</button><button class="secondary" onclick="location.hash='home';location.reload()">Voltar ao site</button></div>`;$('#adminModal').classList.add('open')}
$('#searchBtn').onclick=()=>{$('#searchModal').classList.add('open');$('#searchInput').focus()};$('#closeSearch').onclick=()=>$('#searchModal').classList.remove('open');$('#searchInput').oninput=e=>search(e.target.value);$('#closeDetail').onclick=()=>$('#detailModal').classList.remove('open');$('#adminBtn').onclick=admin;$('#closeAdmin').onclick=()=>$('#adminModal').classList.remove('open');$('#menuBtn').onclick=()=>$('#drawer').classList.toggle('open');$('#themeBtn').onclick=()=>document.body.classList.toggle('light');document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(a=>a.classList.remove('active'));t.classList.add('active');const f=t.dataset.filter;document.querySelectorAll('.card').forEach(c=>{const x=state.items.find(i=>i.id===c.dataset.id);c.style.display=f==='all'||x?.type===f?'':'none'})});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchBtn').click()}});$('#installBtn').onclick=()=>alert('Se o navegador oferecer a instalação, confirme. O modo offline do app shell usa o service worker; episódios protegidos não são baixados.');
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});loadAnime();loadSeries();
