const AUTHORIZED_SOURCES={
  demo:{name:'Vídeo de demonstração (CC0)',type:'video',url:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4'},
  youtube:{name:'YouTube / embed autorizado',type:'iframe',url:'https://www.youtube.com/embed/dQw4w9WgXcQ'}
};
const fallback=[
{id:'solo',title:'Solo Leveling',type:'anime',year:2024,score:8.8,genres:['Ação','Aventura','Fantasia'],episodes:25,image:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=700&q=80',description:'Mais fraco que todos, até que a morte lhe deu uma segunda chance para se tornar o mais forte de todos.',source:'Vídeo de demonstração',sources:[AUTHORIZED_SOURCES.demo]},
{id:'demon',title:'Demon Slayer',type:'anime',year:2019,score:8.6,genres:['Ação','Fantasia'],episodes:63,image:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=80',description:'Tanjiro embarca em uma jornada para proteger sua família.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]},
{id:'jujutsu',title:'Jujutsu Kaisen',type:'anime',year:2020,score:8.5,genres:['Ação','Sobrenatural'],episodes:48,image:'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=700&q=80',description:'Feiticeiros enfrentam maldições sobrenaturais.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]},
{id:'onepiece',title:'One Piece',type:'anime',year:1999,score:9.0,genres:['Aventura','Fantasia'],episodes:1150,image:'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=700&q=80',description:'Uma grande aventura pelos mares em busca do lendário tesouro.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]},
{id:'witcher',title:'The Witcher',type:'series',year:2019,score:8.0,genres:['Fantasia','Drama'],episodes:24,image:'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?auto=format&fit=crop&w=700&q=80',description:'Um caçador de monstros percorre um mundo de magia e criaturas.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]},
{id:'stranger',title:'Stranger Things',type:'series',year:2016,score:8.6,genres:['Drama','Mistério'],episodes:34,image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=700&q=80',description:'Um grupo de amigos se envolve em acontecimentos misteriosos.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]},
{id:'lastofus',title:'The Last of Us',type:'series',year:2023,score:8.7,genres:['Drama','Aventura'],episodes:17,image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=700&q=80',description:'Uma jornada de sobrevivência em um mundo transformado.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]},
{id:'breaking',title:'Breaking Bad',type:'series',year:2008,score:9.5,genres:['Drama','Crime'],episodes:62,image:'https://images.unsplash.com/photo-1534791547706-9a98b9c6c4f5?auto=format&fit=crop&w=700&q=80',description:'Um professor de química toma decisões que mudam sua vida.',source:'Fonte autorizada',sources:[AUTHORIZED_SOURCES.demo]}
];
const defaultSettings={quality:'Auto',autoplay:true,reduceMotion:false,accent:'#7c2cff',accent2:'#b35cff',bg:'#05070a'};
const S={user:JSON.parse(localStorage.getItem('opai_user')||'null'),progress:JSON.parse(localStorage.getItem('opai_progress')||'{}'),favorites:JSON.parse(localStorage.getItem('opai_favorites')||'[]'),settings:{...defaultSettings,...JSON.parse(localStorage.getItem('opai_settings')||'{}')},catalog:[...fallback],reviews:{},cast:{},seasons:{}};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem('opai_progress',JSON.stringify(S.progress));localStorage.setItem('opai_favorites',JSON.stringify(S.favorites));localStorage.setItem('opai_settings',JSON.stringify(S.settings));}
function toast(x){const d=document.createElement('div');d.className='toast';d.innerHTML=x;document.body.appendChild(d);setTimeout(()=>d.remove(),2800)}
function item(id){return S.catalog.find(x=>x.id===id)||fallback[0]}
function pct(id,n){const p=S.progress[id+':'+n];return p?.done?100:p?.pct||0}
function applyTheme(){document.documentElement.style.setProperty('--p',S.settings.accent);document.documentElement.style.setProperty('--p2',S.settings.accent2);document.documentElement.style.setProperty('--bg',S.settings.bg);document.documentElement.style.setProperty('--motion',S.settings.reduceMotion?'0':'1');}
applyTheme();
function card(x,badge=''){return `<article class="card" onclick="details('${esc(x.id)}')"><div class="poster" style="background-image:url('${esc(x.image)}')">${badge?`<span class="badge">${esc(badge)}</span>`:''}<span class="play">▶</span></div><div class="cardbody"><div class="title">${esc(x.title)}</div><div class="meta">${x.year||'—'} · ${x.episodes||'?'} EP <span style="float:right">★ ${Number(x.score||0).toFixed(1)}</span></div>${pct(x.id,3)?`<div class="bar"><i style="width:${pct(x.id,3)}%"></i></div>`:''}</div></article>`}
function epRow(x,n){let p=S.progress[x.id+':'+n]||{};return `<div class="eprow"><b>${n}</b><button class="mini" onclick="event.stopPropagation();play('${esc(x.id)}',${n})">▶</button><div><b>${esc(x.title)}</b> — Episódio ${n}<small>23min · ${p.done?'Assistido':p.pct?p.pct+'%':'Não assistido'}</small></div><span class="status">${p.done?'✓':p.pct?p.pct+'%':'—'}</span><button class="icon" onclick="event.stopPropagation();watch('${esc(x.id)}',${n})">${p.done?'✓':'⋮'}</button></div>`}
function currentSeason(){const m=new Date().getMonth()+1;return m<=3?'winter':m<=6?'spring':m<=9?'summer':'fall'}
function seasonLabel(s){return ({winter:'Inverno',spring:'Primavera',summer:'Verão',fall:'Outono'})[s]||s}
async function jikan(path){const r=await fetch('https://api.jikan.moe/v4/'+path);if(!r.ok)throw new Error('API '+r.status);return r.json()}
function upsertAnime(a){const id='j'+a.mal_id;const old=S.catalog.find(x=>x.id===id);const x={id,mal_id:a.mal_id,title:a.title||a.title_english||'Sem título',type:'anime',year:a.year||a.aired?.prop?.from?.year||new Date().getFullYear(),score:a.score||0,genres:(a.genres||[]).slice(0,4).map(g=>g.name),episodes:a.episodes||12,image:a.images?.jpg?.large_image_url||a.images?.jpg?.image_url,description:a.synopsis||'Informações públicas do catálogo.',source:'Fonte de informação pública',sources:[AUTHORIZED_SOURCES.demo],status:a.status||'',aired:a.aired||null};if(old)Object.assign(old,x);else S.catalog.push(x);return x}
async function catalog(silent=false){try{if(!silent)toast('⟳ Atualizando catálogo e temporada atual...');const season=currentSeason(),year=new Date().getFullYear();const [seasonal,top]=await Promise.all([jikan(`seasons/${year}/${season}?limit=24`),jikan('top/anime?filter=airing&limit=12')]);(seasonal.data||[]).forEach(upsertAnime);(top.data||[]).forEach(upsertAnime);if(!silent)toast(`✓ Catálogo atualizado: ${seasonLabel(season)} ${year}.`)}catch(e){if(!silent)toast('Não foi possível atualizar agora; usando catálogo salvo.')}home()}
function home(){const anime=[...S.catalog.filter(x=>x.type==='anime')];const popular=[...anime].sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,6);const fresh=[...anime].filter(x=>x.year>=new Date().getFullYear()-1).slice(0,6);const series=S.catalog.filter(x=>x.type==='series').slice(0,6);const cont=S.catalog.filter(x=>Object.keys(S.progress).some(k=>k.startsWith(x.id+':')&&S.progress[k].pct&&!S.progress[k].done));const hero=anime.find(x=>x.status?.toLowerCase().includes('currently'))||anime[0]||fallback[0];$('#page').innerHTML=`<section class="hero"><div class="heroart" style="background-image:linear-gradient(90deg,#07090c,transparent),url('${esc(hero.image)}')"></div><div class="herocopy"><small class="authorized">EM DESTAQUE</small><h1>${esc(hero.title)}</h1><div class="meta">${hero.year||'—'} · ${hero.episodes||'?'} episódios · HD · ★ ${Number(hero.score||0).toFixed(1)}</div><div class="chips">${(hero.genres||[]).slice(0,3).map(g=>`<span class="chip">${esc(g)}</span>`).join('')}</div><p>${esc(hero.description)}</p><div class="actions"><button class="primary" onclick="play('${esc(hero.id)}',1)">▶ Assistir</button><button class="ghost" onclick="fav('${esc(hero.id)}')">＋ Minha Lista</button></div></div></section>${cont.length?`<section class="section"><div class="sectionhead"><h2>▣ Continuar assistindo</h2><button onclick="route('history')">Ver tudo →</button></div><div class="grid">${cont.slice(0,6).map(x=>card(x)).join('')}</div></section>`:''}<section class="section"><div class="sectionhead"><h2>🔥 Em Alta</h2><button onclick="route('trending')">Ver todos →</button></div><div class="grid">${popular.map((x,i)=>card(x,i<3?'Novo':'')).join('')}</div></section><section class="section"><div class="sectionhead"><h2>🆕 Novos episódios</h2><button onclick="catalog()">Atualizar ↻</button></div><div class="wide">${fresh.map((x,i)=>`<div class="epcard" onclick="details('${esc(x.id)}')"><div class="thumb" style="background-image:url('${esc(x.image)}')"></div><div><b>${esc(x.title)}</b><small>EP ${Math.max(1,(x.episodes||8)-i)} · ${x.status||'Atualizado'}</small><small>Catálogo ${hero.year===x.year?'atual':'recente'}</small></div></div>`).join('')}</div></section><section class="section"><div class="sectionhead"><h2>⭐ Séries</h2></div><div class="grid">${series.map(x=>card(x)).join('')}</div></section><section class="section"><div class="sectionhead"><h2>📡 Top Airing</h2><span class="meta">Atualizado pela API pública</span></div><div class="top">${popular.slice(0,5).map((x,i)=>`<div class="air" onclick="details('${esc(x.id)}')"><span class="rank">${i+1}</span><div class="airimg" style="background-image:url('${esc(x.image)}')"></div><div><b>${esc(x.title)}</b><div class="meta">${x.status||'Em exibição'} · ★ ${Number(x.score||0).toFixed(1)}</div></div></div>`).join('')}</div></section>`}
function detailTabs(active='episodes'){return `<div class="tabs">${[['episodes','Episódios'],['details','Detalhes'],['seasons','Temporadas'],['cast','Elenco'],['reviews','Avaliações']].map(([k,l])=>`<button class="${active===k?'active':''}" onclick="detailTab('${k}')">${l}</button>`).join('')}</div>`}
function detailBase(x){return `<div class="detail"><div><div class="detailposter" style="background-image:url('${esc(x.image)}')"></div></div><div><div class="meta">Início › ${x.type==='anime'?'Animes':'Séries'} › ${esc(x.title)}</div><h1>${esc(x.title)}</h1><div class="meta">${x.year||'—'} · ${x.episodes||'?'} episódios · HD · ★ ${Number(x.score||0).toFixed(1)}</div><div class="chips">${(x.genres||[]).map(g=>`<span class="chip">${esc(g)}</span>`).join('')}</div><p class="desc">${esc(x.description)}</p><div class="actions"><button class="primary" onclick="play('${esc(x.id)}',1)">▶ Assistir</button><button class="ghost" onclick="fav('${esc(x.id)}')">＋ Minha Lista</button></div><p class="meta">♧ Player somente por fontes autorizadas/embeds permitidos.</p>${detailTabs('episodes')}<div id="detailPanel"></div></div><aside><div class="source"><b>ONDE ASSISTIR</b><div class="sourceitem"><span>◉ ${esc(x.source)}</span><small class="authorized">Informação</small></div><p class="meta">Embeds precisam estar em HTTPS e pertencer à allowlist.</p></div></aside></div>`}
function details(id){const x=item(id);$('#page').innerHTML=detailBase(x);renderDetailPanel('episodes',x);scrollTo(0,0)}
async function detailTab(tab){const currentId=$('#detailPanel')?.dataset?.id;const x=currentId?item(currentId):S.catalog.find(a=>document.querySelector('.detail h1')?.textContent===a.title);if(!x)return;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase().startsWith(({episodes:'epis',details:'detal',seasons:'tempor',cast:'elenco',reviews:'avalia'})[tab])));renderDetailPanel(tab,x)}
function renderDetailPanel(tab,x){const panel=$('#detailPanel');if(!panel)return;panel.dataset.id=x.id;if(tab==='episodes')panel.innerHTML=`<div class="seasons"><div><button class="season active" onclick="seasonSelect('${esc(x.id)}',1,this)"><b>Temporada 1</b><small>${Math.min(12,x.episodes||12)} episódios</small></button><button class="season" onclick="seasonSelect('${esc(x.id)}',2,this)"><b>Temporada 2</b><small>${Math.min(13,Math.max(0,(x.episodes||13)-12))} episódios</small></button></div><div id="episodeList" class="eplist">${Array.from({length:Math.min(8,x.episodes||8)},(_,i)=>epRow(x,i+1)).join('')}</div></div>`;else if(tab==='details')panel.innerHTML=`<div class="info-grid"><div class="setting"><b>Informações</b><p>Tipo: ${esc(x.type)}</p><p>Ano: ${x.year||'—'}</p><p>Status: ${esc(x.status||'Informação pública')}</p><p>Episódios: ${x.episodes||'—'}</p><p>Nota: ★ ${Number(x.score||0).toFixed(1)}</p></div><div class="setting"><b>Sinopse</b><p class="desc">${esc(x.description)}</p><p class="meta">Dados puxados automaticamente de fonte pública de informações.</p></div></div>`;else if(tab==='seasons')panel.innerHTML=`<div class="season-grid"><button class="season active" onclick="seasonSelect('${esc(x.id)}',1,this)"><b>Temporada 1</b><small>${Math.min(12,x.episodes||12)} episódios</small></button><button class="season" onclick="seasonSelect('${esc(x.id)}',2,this)"><b>Temporada 2</b><small>${Math.min(13,Math.max(0,(x.episodes||13)-12))} episódios</small></button></div><div id="seasonEpisodes" class="eplist"></div>`;else if(tab==='cast')renderCast(x,panel);else if(tab==='reviews')renderReviews(x,panel)}
async function seasonSelect(id,n,btn){const x=item(id);const target=$('#episodeList')||$('#seasonEpisodes');if(!target)return;document.querySelectorAll('.season').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');const count=Math.min(n===1?12:13,Math.max(0,(x.episodes||12)-(n-1)*12));target.innerHTML=count?Array.from({length:Math.min(count,13)},(_,i)=>epRow(x,(n-1)*12+i+1)).join(''):'<div class="empty">Esta temporada ainda não possui episódios cadastrados.</div>'}
async function renderCast(x,panel){if(!x.mal_id){panel.innerHTML='<div class="empty">Elenco detalhado disponível quando o título vier da fonte de informações.</div>';return}panel.innerHTML='<div class="loading">Carregando elenco...</div>';try{const j=await jikan(`anime/${x.mal_id}/characters`);S.cast[x.id]=j.data||[];panel.innerHTML=`<div class="castgrid">${(j.data||[]).slice(0,18).map(c=>`<div class="castcard"><img src="${esc(c.character?.images?.jpg?.image_url||'')}" alt=""><div><b>${esc(c.character?.name||'Personagem')}</b><small>${esc(c.role||'Elenco')}</small>${c.voice_actors?.[0]?.person?.name?`<small>Voz: ${esc(c.voice_actors[0].person.name)}</small>`:''}</div></div>`).join('')||'<div class="empty">Nenhum elenco disponível.</div>'}</div>`}catch(e){panel.innerHTML='<div class="empty">Não foi possível carregar o elenco agora.</div>'}}
async function renderReviews(x,panel){if(!x.mal_id){panel.innerHTML='<div class="empty">Avaliações detalhadas disponíveis quando o título vier da fonte de informações.</div>';return}panel.innerHTML='<div class="loading">Carregando avaliações...</div>';try{const j=await jikan(`anime/${x.mal_id}/reviews?limit=8`);S.reviews[x.id]=j.data||[];panel.innerHTML=`<div class="reviews-head"><b>Avaliações públicas</b><span class="meta">Nota geral: ★ ${Number(x.score||0).toFixed(1)}</span></div><div class="reviewlist">${(j.data||[]).map(r=>`<article class="review"><div class="reviewtop"><b>${esc(r.user?.username||'Usuário')}</b><span>★ ${r.score||'—'}</span></div><small>${esc(r.date||'')}</small><p>${esc((r.review||'').slice(0,600))}${(r.review||'').length>600?'…':''}</p></article>`).join('')||'<div class="empty">Nenhuma avaliação pública disponível.</div>'}</div>`}catch(e){panel.innerHTML='<div class="empty">Não foi possível carregar as avaliações agora.</div>'}}
function getSources(x,n){const custom=(x.sources||[]).filter(s=>s&&s.url);return custom.length?custom:[AUTHORIZED_SOURCES.demo]}
function safeUrl(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:''}catch{return ''}}
function playerMarkup(source,x,n){const url=safeUrl(source.url);if(!url)return `<div class="playererror">Fonte inválida. O player aceita somente URLs HTTPS.</div>`;if(source.type==='iframe')return `<iframe class="embedframe" src="${esc(url)}" title="Player de ${esc(x.title)} episódio ${n}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>`;return `<video id="videoPlayer" class="videoplayer" controls playsinline preload="metadata" ${S.settings.autoplay?'autoplay':''} src="${esc(url)}"></video>`}
function play(id,n,sourceIndex=0){const x=item(id),sources=getSources(x,n),source=sources[sourceIndex]||sources[0],key=id+':'+n,saved=S.progress[key]?.seconds||0;$('#page').innerHTML=`<div class="player-head"><button class="ghost" onclick="details('${esc(x.id)}')">← Voltar</button><div><div class="meta">${esc(x.title)} · T1 · EP ${n}</div><h2>${esc(x.title)} — Episódio ${n}</h2></div></div><div class="player-shell"><div class="sourcebar"><b>Fontes de reprodução</b><div class="sourcebuttons">${sources.map((s,i)=>`<button class="sourcebtn ${i===sourceIndex?'active':''}" onclick="play('${esc(x.id)}',${n},${i})">${esc(s.name||'Fonte')}</button>`).join('')}</div></div><div class="player">${playerMarkup(source,x,n)}${source.type==='video'?`<div class="playeroverlay"><span>Fonte: ${esc(source.name||'Fonte autorizada')}</span><span class="authorized">HTTPS · autorizada</span></div>`:''}</div><div class="player-actions"><span class="meta">O episódio é marcado automaticamente quando o vídeo termina ou chega a 90%.</span><button class="ghost" onclick="watch('${esc(x.id)}',${n})">✓ Marcar como assistido</button></div><div class="note">🔐 O player aceita apenas embeds HTTPS configurados como fontes autorizadas.</div></div><section class="section"><div class="sectionhead"><h2>Temporada 1</h2></div><div class="eplist">${Array.from({length:Math.min(8,x.episodes||8)},(_,i)=>epRow(x,i+1)).join('')}</div></section>`;const video=$('#videoPlayer');if(video){if(saved>0)video.addEventListener('loadedmetadata',()=>{try{video.currentTime=Math.min(saved,Math.max(0,video.duration-1))}catch{}});let savedAt=0;const persist=()=>{const pct=video.duration?Math.round(video.currentTime/video.duration*100):0;S.progress[key]={pct,done:S.progress[key]?.done||false,seconds:Math.floor(video.currentTime),updatedAt:Date.now()};save()};video.addEventListener('timeupdate',()=>{if(Date.now()-savedAt>3000){savedAt=Date.now();persist()}if(video.duration&&video.currentTime/video.duration>=.9&&!S.progress[key]?.done){S.progress[key]={pct:100,done:true,seconds:Math.floor(video.currentTime),updatedAt:Date.now()};save();toast('✓ Episódio marcado como assistido automaticamente.')}});video.addEventListener('ended',()=>{S.progress[key]={pct:100,done:true,seconds:Math.floor(video.duration||0),updatedAt:Date.now()};save();toast('✓ Episódio concluído e marcado como assistido.')})}scrollTo(0,0)}
function watch(id,n){const k=id+':'+n;S.progress[k]={pct:S.progress[k]?.done?0:100,done:!S.progress[k]?.done,seconds:S.progress[k]?.seconds||0,updatedAt:Date.now()};save();toast(S.progress[k].done?'Episódio marcado como assistido.':'Episódio desmarcado.');details(id)}
function fav(id){const i=S.favorites.indexOf(id);i>=0?S.favorites.splice(i,1):S.favorites.push(id);save();toast(i>=0?'Removido da lista.':'Adicionado à sua lista.')}
function route(r){document.querySelectorAll('#nav>button,[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===r));if(r==='home')return home();let a=S.catalog;if(r==='anime')a=S.catalog.filter(x=>x.type==='anime');if(r==='series')a=S.catalog.filter(x=>x.type==='series');if(r==='films')a=[];if(r==='trending')a=[...S.catalog].sort((x,y)=>(y.score||0)-(x.score||0));if(r==='favorites')a=S.catalog.filter(x=>S.favorites.includes(x.id));if(r==='history')a=S.catalog.filter(x=>Object.keys(S.progress).some(k=>k.startsWith(x.id+':')));if(r==='downloads')return $('#page').innerHTML='<div class="empty">Downloads só devem aparecer quando uma fonte autorizada fornecer download permitido.</div>';if(r==='calendar')return $('#page').innerHTML='<div class="stats">'+['Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].map((d,i)=>`<div class="stat"><small>${d}</small><strong>EP ${8+i}</strong><span class="meta">${esc(S.catalog[i%S.catalog.length]?.title||'')}</span></div>`).join('')+'</div>';if(r==='new')a=[...S.catalog].sort((x,y)=>(y.year||0)-(x.year||0));if(r==='admin')return admin();$('#page').innerHTML=`<div class="sectionhead"><h2>${r==='anime'?'Animes':r==='series'?'Séries':r==='trending'?'Em Alta':r==='favorites'?'Favoritos':r==='history'?'Histórico':'Catálogo'}</h2></div>${a.length?`<div class="grid">${a.map(x=>card(x)).join('')}</div>`:'<div class="empty">Nenhum título encontrado.</div>'}`}
function admin(){if(S.user?.role!=='admin')return home();$('#page').innerHTML=`<div class="sectionhead"><div><h2>♜ Painel de Administração</h2><small>Somente administrador</small></div><button class="primary" onclick="catalog()">↻ Atualizar catálogo</button></div><div class="stats">${[['Animes',S.catalog.filter(x=>x.type==='anime').length],['Episódios','24.893'],['Usuários','5.631'],['Visualizações','1.234.567']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong><span class="meta">Dados do projeto</span></div>`).join('')}</div><section class="section"><div class="settings"><div class="setting"><b>Catálogo</b><p class="meta">Atualizar temporada atual, animes em exibição e Top Airing usando informações públicas.</p><button class="primary" onclick="catalog()">Atualizar agora</button></div><div class="setting"><b>Fontes</b><p class="meta">Allowlist para embeds HTTPS autorizados.</p><span class="authorized">Proteção ativa</span></div><div class="setting"><b>Usuários</b><p class="meta">Gerencie permissões no backend em produção.</p></div><div class="setting"><b>Logs</b><p class="meta">Auditoria administrativa.</p></div></div></section>`}
function settings(){const s=S.settings;$('#modal').innerHTML=`<div class="modalbg" onclick="if(event.target===this)closeModal()"><div class="modalbox"><div class="modalhead"><div><h2>Personalização e configurações</h2><small>As cores ficam salvas neste dispositivo.</small></div><button class="icon" onclick="closeModal()">×</button></div><div class="settings"><div class="setting"><b>Cor principal</b><input class="colorpicker" id="accent" type="color" value="${esc(s.accent)}"><small>Botões, destaques e navegação</small></div><div class="setting"><b>Cor secundária</b><input class="colorpicker" id="accent2" type="color" value="${esc(s.accent2)}"><small>Gradientes e detalhes</small></div><div class="setting"><b>Cor de fundo</b><input class="colorpicker" id="bg" type="color" value="${esc(s.bg)}"><small>Fundo geral do site</small></div><div class="setting"><b>Presets</b><div class="presetrow"><button class="ghost" onclick="preset('purple')">Roxo</button><button class="ghost" onclick="preset('blue')">Azul</button><button class="ghost" onclick="preset('red')">Vermelho</button><button class="ghost" onclick="preset('green')">Verde</button></div></div></div><label>Qualidade<select id="quality"><option>Auto</option><option>1080p</option><option>720p</option><option>480p</option></select></label><label><input id="autoplay" type="checkbox" ${s.autoplay?'checked':''}> Reprodução automática</label><label><input id="reduce" type="checkbox" ${s.reduceMotion?'checked':''}> Reduzir animações (desempenho)</label><button class="primary full" onclick="saveSettings()">Salvar configurações</button></div></div>`;$('#quality').value=s.quality}
function preset(name){const p={purple:['#7c2cff','#b35cff','#05070a'],blue:['#2563eb','#60a5fa','#030712'],red:['#dc2626','#fb7185','#090505'],green:['#16a34a','#4ade80','#030805']}[name];if(!p)return;$('#accent').value=p[0];$('#accent2').value=p[1];$('#bg').value=p[2];document.documentElement.style.setProperty('--p',p[0]);document.documentElement.style.setProperty('--p2',p[1]);document.documentElement.style.setProperty('--bg',p[2])}
function saveSettings(){S.settings={quality:$('#quality').value,autoplay:$('#autoplay').checked,reduceMotion:$('#reduce').checked,accent:$('#accent').value,accent2:$('#accent2').value,bg:$('#bg').value};save();applyTheme();closeModal();toast('✓ Personalização e configurações salvas.')}
function closeModal(){$('#modal').innerHTML=''}
function register(){const u=prompt('Novo usuário');if(!u)return;const p=prompt('Senha (mínimo 6 caracteres)');if(!p||p.length<6)return toast('Senha inválida.');localStorage.setItem('opai_user_'+u,JSON.stringify({user:u,role:'user'}));toast('Conta criada. Agora faça login.')}
function login(e){e.preventDefault();const u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(u==='admin'&&p==='cauhub123')S.user={user:'admin',role:'admin'};else{const a=JSON.parse(localStorage.getItem('opai_user_'+u)||'null');if(!a||!p)return toast('Usuário ou senha inválidos.');S.user=a}localStorage.setItem('opai_user',JSON.stringify(S.user));start()}
function start(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#adminNav').classList.toggle('hidden',S.user?.role!=='admin');catalog(true)}
function search(q){q=q.toLowerCase().trim();if(!q)return home();const a=S.catalog.filter(x=>(x.title+' '+(x.genres||[]).join(' ')).toLowerCase().includes(q));$('#page').innerHTML=`<div class="sectionhead"><h2>Resultados para “${esc(q)}”</h2></div>${a.length?`<div class="grid">${a.map(x=>card(x)).join('')}</div>`:'<div class="empty">Nenhum título encontrado.</div>'}`}
$('#loginForm').onsubmit=login;$('#createAccountBtn').onclick=register;$('#togglePass').onclick=()=>$('#loginPass').type=$('#loginPass').type==='password'?'text':'password';$('#forgotBtn').onclick=()=>toast('No modo demo, a recuperação deve ser ligada ao backend.');$('#settings').onclick=settings;$('#searchBtn').onclick=()=>search($('#search').value);$('#search').onkeydown=e=>e.key==='Enter'&&search(e.target.value);$('#random').onclick=()=>details(S.catalog[Math.floor(Math.random()*S.catalog.length)].id);$('#openSidebar').onclick=()=>$('#sidebar').classList.add('open');$('#closeSidebar').onclick=()=>$('#sidebar').classList.remove('open');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route(b.dataset.route);$('#sidebar').classList.remove('open')});$('#profile').onclick=()=>toast(`Conta: <b>${esc(S.user?.user||'usuário')}</b>`);if(S.user)start();
