/* OPAI HUB - melhorias sem substituir o núcleo existente */
(function(){
  const safe=(u)=>{try{const x=new URL(u);return x.protocol==='https:'?x.href:''}catch{return ''}};
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  window.OPAI_ALLOWED_HOSTS=new Set(['interactive-examples.mdn.mozilla.net','www.youtube.com','www.youtube-nocookie.com','player.vimeo.com']);
  window.OPAI_isAllowedSource=function(url){const clean=safe(url);if(!clean)return false;try{return OPAI_ALLOWED_HOSTS.has(new URL(clean).hostname)}catch{return false}};

  window.play=function(id,n=1,sourceIndex=0){
    const x=typeof item==='function'?item(id):null;if(!x)return;
    const sources=(x.sources||[]).filter(s=>s&&s.url&&OPAI_isAllowedSource(s.url));
    if(!sources.length){toast('Nenhuma fonte autorizada disponível para este episódio.');return}
    const source=sources[sourceIndex]||sources[0],key=id+':'+n,saved=S.progress[key]?.seconds||0;
    $('#page').innerHTML=`<div class="player-head"><button class="ghost" onclick="details('${esc(id)}')">← Voltar</button><div><div class="meta">${esc(x.title)} · T1 · EP ${n}</div><h2>${esc(x.title)} — Episódio ${n}</h2></div></div><div class="player-shell"><div class="sourcebar"><b>Fontes autorizadas</b><div class="sourcebuttons">${sources.map((s,i)=>`<button class="sourcebtn ${i===sourceIndex?'active':''}" onclick="play('${esc(id)}',${n},${i})">${esc(s.name||'Fonte autorizada')}</button>`).join('')}</div></div><div class="player" id="opaiPlayer">${source.type==='iframe'?`<iframe class="embedframe" src="${esc(safe(source.url))}" title="${esc(x.title)} episódio ${n}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>`:`<video id="videoPlayer" class="videoplayer" controls playsinline preload="metadata" ${S.settings.autoplay?'autoplay':''} src="${esc(safe(source.url))}"></video>`}</div><div class="player-actions"><span class="meta">Progresso salvo automaticamente. Ao terminar ou chegar a 90%, o episódio fica como assistido.</span><button class="ghost" onclick="watch('${esc(id)}',${n})">✓ Marcar como assistido</button></div><div class="note">🔐 Reprodução limitada a hosts HTTPS autorizados pelo projeto.</div></div><section class="section"><div class="sectionhead"><h2>Temporada 1</h2></div><div class="eplist">${Array.from({length:Math.min(8,x.episodes||8)},(_,i)=>epRow(x,i+1)).join('')}</div></section>`;
    const video=$('#videoPlayer');if(video){video.addEventListener('loadedmetadata',()=>{if(saved>0){try{video.currentTime=Math.min(saved,Math.max(0,video.duration-1))}catch{}}});let lastSave=0;const persist=()=>{const pct=video.duration?Math.round(video.currentTime/video.duration*100):0;S.progress[key]={...(S.progress[key]||{}),pct,seconds:Math.floor(video.currentTime),updatedAt:Date.now()};save()};video.addEventListener('timeupdate',()=>{if(Date.now()-lastSave>3000){lastSave=Date.now();persist()}if(video.duration&&video.currentTime/video.duration>=.9&&!S.progress[key]?.done){S.progress[key]={pct:100,done:true,seconds:Math.floor(video.currentTime),updatedAt:Date.now()};save();toast('✓ Episódio marcado como assistido automaticamente.')}});video.addEventListener('ended',()=>{S.progress[key]={pct:100,done:true,seconds:Math.floor(video.duration||0),updatedAt:Date.now()};save();toast('✓ Episódio concluído e marcado como assistido.')});video.addEventListener('error',()=>toast('A fonte autorizada não pôde ser reproduzida neste navegador.'))}scrollTo(0,0);
  };

  window.detailTab=function(tab){const panel=$('#detailPanel');if(!panel)return;const id=panel.dataset.id,x=id&&typeof item==='function'?item(id):null;if(!x)return;document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));const labels={episodes:'Episódios',details:'Detalhes',seasons:'Temporadas',cast:'Elenco',reviews:'Avaliações'};document.querySelectorAll('.tabs button').forEach(b=>{if(b.textContent.trim()===labels[tab])b.classList.add('active')});renderDetailPanel(tab,x)};

  const oldSettings=window.settings;
  window.settings=function(){oldSettings();setTimeout(()=>{const box=document.querySelector('.modalbox');if(!box)return;const extra=document.createElement('div');extra.className='setting interface-extra';extra.innerHTML=`<b>Interface</b><label class="inlinecheck"><input id="compactMode" type="checkbox" ${S.settings.compact?'checked':''}> Modo compacto</label><label class="inlinecheck"><input id="largerText" type="checkbox" ${S.settings.largerText?'checked':''}> Texto maior</label>`;const grid=box.querySelector('.settings');if(grid)grid.appendChild(extra);const saveBtn=box.querySelector('.primary.full');if(saveBtn){const original=saveBtn.onclick;saveBtn.onclick=function(){if(original)original.call(this);S.settings.compact=!!$('#compactMode')?.checked;S.settings.largerText=!!$('#largerText')?.checked;save();applyInterfacePrefs()}}},0)};
  function applyInterfacePrefs(){document.documentElement.classList.toggle('compact-ui',!!S.settings.compact);document.documentElement.classList.toggle('large-text-ui',!!S.settings.largerText)}
  applyInterfacePrefs();
  const settingsButton=$('#settings');if(settingsButton)settingsButton.onclick=window.settings;
  setInterval(()=>{if(S.user&&typeof catalog==='function')catalog(true)},30*60*1000);
})();
